### ISSUE TITLE
findRelationshipsByProperty returning more than a pageSize of results

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria-connector-ibm-information-server#213] opened 2020-01-20 13:38 UTC
When calling the above method it seems to be capable of returning a result with more entries than the designated pageSize.

A concrete example is when searching for relationships of type "SemanticAssignment".

In the IGC repository being used in the CTS/IGC connector test, there appear to be 18 instances of relationship type SemanticAssignment. In the CTS relationship search test case a find... is issued with the following parameters:

typeGUID is set to null - meaning relationships instances of any type can be returned
matchProperties contains "confidence" set to a value of 100.
pageSize is set to 10

The result returned contains 31 instances:
3.  : ForeignKey
18 : SemanticAssignment
10 : DataClassAssignment

Note that this is a "wild" test - in that it does not specify a type filter. The result may therefore be an aggregate of separate underlying type-specific queries, which could lead to a result greater than pageSize. However, the result contains more than the pageSize of instances of type Semantic~Assignment, so it appears that even a sub-query can find and return more than pageSize instances.

Side-note: I could make the CTS resilient to getting back more instances than it is expecting but as things stand it is proving to be quite a good test.

In another test, I noticed that relationships of type DataClassAssignment can also exceed the pageSize limit, when searched for with the appropriate typeGUID and an empty MatchProperties parameter. In this test pageSize is also set to 10, but 53 instances were returned.

I'm happy to reproduce and provide screen captures etc if it helps.

**Comment by cmgrote** [comment] 2020-01-20 14:17
Definitely looks like a bug -- I vaguely remember fixing something similar (maybe on the entities search side?) already, so perhaps I just missed the fix for the relationships side.  I'll have a deeper look.  Thanks!

**Comment by cmgrote** [comment] 2020-01-29 20:10
I believe this one is now fixed by a previous PR, as I haven't been able to reproduce in the last several test runs -- will close for now, but can re-open if we hit it again.

**Closed by cmgrote** 2020-01-29 20:10 UTC
Labels: bug
